# Data Preprocessing Tools

## Importing the libraries

In [97]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [98]:
dataSet = pd.read_csv('Data.csv')
X = dataSet.iloc[:, :-1].values
Y = dataSet.iloc[:, -1].values

In [99]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [100]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [101]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [102]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [103]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [104]:
print(x)

[[0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 40.0 nan]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 nan 52000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [105]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [106]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [107]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [108]:
print(X_train)

[['Spain' 38.77777777777778 52000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 44.0 72000.0]
 ['Spain' 38.0 61000.0]
 ['Spain' 27.0 48000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 35.0 58000.0]]


In [109]:
print(X_test)

[['Germany' 30.0 54000.0]
 ['France' 37.0 67000.0]]


In [110]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [111]:
print(y_test)

[0 1]


## Feature Scaling

In [115]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()


ValueError: Found array with 0 feature(s) (shape=(8, 0)) while a minimum of 1 is required by StandardScaler.

In [113]:
print(X_train)

[['Spain' 38.77777777777778 52000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 44.0 72000.0]
 ['Spain' 38.0 61000.0]
 ['Spain' 27.0 48000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 35.0 58000.0]]


In [114]:
print(X_test)

[['Germany' 30.0 54000.0]
 ['France' 37.0 67000.0]]
